language: haskell
branches:
  only:
    - source
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
install:
  - wget https://github.com/commercialhaskell/stack/releases/download/v1.0.0/stack-1.0.0-linux-x86_64.tar.gz -O stack.gz
  - tar xvf stack.gz
  - chmod +x stack-1.0.0-linux-x86_64/stack
  - stack-1.0.0-linux-x86_64/stack setup
  - stack-1.0.0-linux-x86_64/stack build
before_script:
  - git config --global user.name 'Build Bot'
  - git config --global user.email 'build@hackconf.in'
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - mkdir deploy/
script:
  - .stack-work/install/x86_64-linux/lts-2.0/7.8.4/bin/navya-website build
after_script:
  - cp -r _site/* deploy/
  - cd deploy/
  - git init -q
  - git checkout --orphan master -q
  - git remote add origin $REPO
  - git add --all .
  - git commit -m "generated on `date`"
  - git push origin master --force -q
after_success: true
env:
  global:
  - REPO="git@github.com:navya/navya.github.io.git"
  - secure: "kiAugqk6lUrpZuAKiTUYXd+1UhhoFC09EyOpmP4wgI9vmkouPxDutjIeLudFM+RfRNRaP42GjC9Au7W8mADyRKnb/2S5+hRjyhBYOsKnoBNvYzKlg5LfQ1dC8eU+LmUg8YFIl5mrcRYoMAWX7EIs44lpsCkwo9BDFJQuduzPHXU="
  - secure: "gcaheHZFM3BTKshUQWwpNYrx1N4kviqLRTCtanQRLps3j3zqNLCG2zLljkIGa05QCiuBgLLAiGZK7g8I0rpMn6yKBXkJ5hZjdjB7SJP2aM1jkeUbxdBPKbsQNRhwBu3bIMXPsdtWfClfQT5drPyGJBYZJepVGh6aDR2W1iJMP1A="
  - secure: "SILSi/n+5aY1Cp83jh2oFD/+OW3Ief9F26q9BxzlBWxch04hjUuGAiNTT7ckE+8fMJJNqMUIZRZeKEtnIL1VM/9K4RR546wv9ROuFP81p4H56NXrLiiOvWBhBDbZEnu498+tgxgAppxbLWcL2Qnf7LIV+EsVjyV+yxFx2MHdNWI="
  - secure: "KCSoCqQutlT5dzCnbwYC5ChqyXzyWR5CD6C2vJGCqfQTCs2EFcBAz8SYnj7iiGR5LBU85l2IaCd2yD+JLyxoQ9snfs73ll151IRvO54ZtT8TKJmq3TzfiSaqOCH0GJDF5XMzmncuJiOAID4B+LPzkzMujUP+C2W/Cvb8nHSYhcY="
  - secure: "SqqdkDRPONOhIVGIFiF3s+cdFlkk1YBdo7AooYEuP1sEaRpD9l8ZF41Te52TSNvLAhdDNHkRAp4C5TMd4Yua3mWnkr1pwI3sY5IvRknDfGN8i26tyZ7jrw5T3w/dr69X5hhdr2Fj/06uaANZ7NUPgpWCCk7f6LIayWSVBsK99hA="
  - secure: "Uh3sYK0mHk4xCw5yx+UPP4mWfjZgws6qH+qKQp1is8PFePSKnaUGSd7FQsimzNCPho4GbMkfloRfkF3970hnuKjK5odSNK6oIbjKoM3kzuNGoA28gLqCqXH4aXOBm9BAaGuWb9APTZEhW4vHlTgMpBxkarD6h8pwXVTBx04NPdA="
  - secure: "bbNq8k8nbbCjB+b2Vy848PKe3hg29ZDD5Y3knAjx9mBYcAD/z1TBulpPaf6YMgun6KYG1U1r6WroKy+Wxysat9tDs0zsKICxMIEQw+8vAdiolU4NyxXzyr1s+he+9afAMX5XODKAfEeiGed/Td2OUMvqktf86apNp+dSZ5r8F1o="
  - secure: "MCWfJH/N/APuja0eE0HeB/K551KIaNmJwnac8Ew8mi78Y6qsMeT3JInLqOFb8En9MxsjDpfDe8Vg4mhru+y35ivAbDk0iLSz2HkWckT3rwpqQRhlEaPIcupdc9qGPrX+HlixTpH8fiC307J4UqqN/z47jvpbZK/ToWDrkxhndb0="
  - secure: "AR9PmcmoqU5eWxp0SKHDEzWwqbLlAC49FOT3l5zE4IbkXdWTsgNz0LXA2fui+Kh++r7Q7ZpcvP8ceGlqYTjdo11m/nkmMj3bAKP1TKh1LAC/7Toh3nfYhL6hB1B8Of9nlTrm2ZtPFOoY4Vz/qaMATjoOilToSF/vn+zWd9vAL+E="
  - secure: "FjzwT17nbNUWiF/p9bdHzd1Jcyh23xkegwu/MDSYLsUIww8ABmlca5NvHSQLXnoQ0RS+QfAOILHCI5YUCfEu6IMDoWthCrlOdUV+kQMwekQ8Al/d4QTsQs3TsDwoyNVA64c/E178GR/K+Rc2NIgsKYNM33+Ur0rWnaUdPG5Ny3o="
  - secure: "HgLtKRqKMW0Ub6KomEdRwtJXy1aSgKBlrhkNcfaE0eySrjk0wFHV3lbXaqDRtE6Byp+9PTIwjIekaN5dKREBJPGXv5SS2cwuK80ymDUEy7hgKZRdCr8qXUpQJuawCeg3MOXSkKLMqoDBJxjIRBdsVko7peoccG3pERZgdT5RjYA="
  - secure: "LptzS2Byvd/VV62aVxLk/7yvvogtM9b1j9xxLYPhNChg56p6LYIxJZYDfi4CUS6Da8zZ9EKy5yI/6RtXnHebNdZq7IV5laPUpOcbRzVoRbtN9BnVyetC5MRAgr4YBMybAzoPRPcSpX4gO5T4ugkFQlrjDmZs4jRNa9DHqxQ0kcM="
  - secure: "PRetWh3RrvenlIiNud+OrERfYUENebP6RVdH5iSbjxgXoCmL9wamVDBl+K5neGn82uCeG/u+7zoBqyiGVzKubeQfia0RJ2J4qn6Eip5KDsgM4NxuT6wNKthlEcEeXXf2bnMBxqNWFbrq7WZYGZsx4QDchUyY7aZewsx8jiYuzOU="
  - secure: "jBY7Zx3AP05qRNsh3EBUvlPQO6X1HjsbxgHQGs26H506lOy8mK4pFAuA3aCo+Coc9Ibp0o6DFsdx90TWWG2x+X9dIB91MiBXZOYpn2Ljrw5JoliqjtSW+6CJWGic27+v4Fa5E5kQC3/JrhrUYsYGfc8pbtCRiM4zMiXed2hToT4="
  - secure: "haAvj2gzNXhSKIlT1WcIKeZzn9kDmC1108VYlS/4QLDjU1LD+2UGd9ASaq6HczPM8etjajp7SOR8SkB6VeAmP8o6O94bIep6wqAstz0v9BwqVlld3WHCnKa9FI2V29TRnyg8GV5y9TBizEOCLDCxXvO6lCeMwaU9/SIaP4lw8mo="
  - secure: "bmCq8lIZQ3DXW2CqvkIOFLk42y3Xelgw0OdnOwidbtNfH9+Yps46XrdvgqvYGDp4mHWBLd142v1/KJlU3nvn2VnkUT/4dlm4iqbQRKtJwovRS4nReEdv6loMAQKOrbtkHT9My1FqjTpkb6GeNMqMTwT+MtjowFIKQxb/5dQMr0A="
  - secure: "Nafu0ovhsmHmGhL1ikndhrfsrqCB68/0lwxWK7+lKahrw33oNAlX3FlUIDqoTY7RjZKde4O57RLyC+OSO6GoBLnjmGGAQszFdgrnPTRJ3AZAeIEh7FA2pd/e0WVgXzPx4HFc9y/Xu741uVIPZMTDsR28TRYbn3A1unLkmU1p+xk="
  - secure: "EJIFdM8DJ2TYEpYJmSWFQwjAPkZy5A3+EroHo+9f4r991VXFKyjOkkdJ8URYRMPoEcBvM7dbQb7cvsNb8SCz9uXD2yIs6zmV8ENsf0gNQEOdiFsTzYVzat3uHqHipzWIZaRQx8bavYq/tnqzwgxw+Me33Bz6HnFxqqtLsll+84s="
  - secure: "Z0isnjdUYfR3lGRVf1irvMPTlco08qAiIT+lpezvq6/5AIsrdLcYMspKmjYETzllVsQ6L2GqZUWDyJ3IoXgIARX9EP8HB/jJVckOgERMjvqvzvd8qDaYmB+B2G6y26rpNplWvydI/vSwBP58k1Eh5fmnL9wqQBteHofgfwQnMkA="
  - secure: "AlOjO7VrLa0cYdrDcodDcgizGerugQvqGEtcqiIm8pvAmuiwyXPJknNBhOj1BaneMXWM2HoZrk+gydbOWnaAVbnG6CCInyvnta9RO4jKskzXK8HiWN7G2xFV4eSp687euTymGiwjD+nSM8+c3mOkcLuvfMAaRkPdasl3sg4dx6E="
  - secure: "grtHCvFmNX/+8xI9qUwWY7cP1IndGtvKN+YxiMR06PVfXlGfO8dMCXpgXGW96kjco7MZGPYc6pdnDfvqAuakmRbmz0JEw/rbK0ow+vAhMCyMcMQ8h2IYyo8xOJPIsct8rdv4n0XVzVY3PpvryX6nRcjBMfm8GjgfMFu4y9NuU+4="
  - secure: "LQGyBiB+1UBMsEuedo/FSp9UsUa1ZMXR7Ii6uundQrKZzGS72uJzZqWbcLV5gFOEKRufknHqMaebg0zGQPycAQZAXu3EVzStHlAhmEi9fjBT2/iNbKs4RgaeRvWi5oOh6ZWmTO1abOnKLskV2DXhsytWbnfhFG5BDyg7HjwsC6g="
  - secure: "NTnHgfnpCRG7DUDF73CD8EDwue9HltrRxp4WMLlGZrkmzI8P4jD0e/8KIFUJDPKCCdp0zs6jc9AOojiPXi2ti7ni/atXttUzo4OauS+fs9bZBUHrC+jdnaxUIs0SiFb7rrHtw0fy6VjI9ca0n4r8gtZC5OtMErbOrE/z/Uj6UR0="
